package com.ss.domain;

public class TtfPinyins {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttf_pinyins.id
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttf_pinyins.word
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ttf_pinyins.py
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    private String py;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttf_pinyins.id
     *
     * @return the value of ttf_pinyins.id
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttf_pinyins.id
     *
     * @param id the value for ttf_pinyins.id
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttf_pinyins.word
     *
     * @return the value of ttf_pinyins.word
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttf_pinyins.word
     *
     * @param word the value for ttf_pinyins.word
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ttf_pinyins.py
     *
     * @return the value of ttf_pinyins.py
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    public String getPy() {
        return py;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ttf_pinyins.py
     *
     * @param py the value for ttf_pinyins.py
     *
     * @mbg.generated Fri Mar 16 16:35:44 CST 2018
     */
    public void setPy(String py) {
        this.py = py;
    }
}