package com.ss.dao;

import com.ss.domain.TtfPinyins;

import java.util.List;

public interface TtfPinyinsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttf_pinyins
     *
     * @mbg.generated Fri Mar 16 13:47:43 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttf_pinyins
     *
     * @mbg.generated Fri Mar 16 13:47:43 CST 2018
     */
    int insert(TtfPinyins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttf_pinyins
     *
     * @mbg.generated Fri Mar 16 13:47:43 CST 2018
     */
    int insertSelective(TtfPinyins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttf_pinyins
     *
     * @mbg.generated Fri Mar 16 13:47:43 CST 2018
     */
    TtfPinyins selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttf_pinyins
     *
     * @mbg.generated Fri Mar 16 13:47:43 CST 2018
     */
    int updateByPrimaryKeySelective(TtfPinyins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ttf_pinyins
     *
     * @mbg.generated Fri Mar 16 13:47:43 CST 2018
     */
    int updateByPrimaryKey(TtfPinyins record);

    List<TtfPinyins> getAll();
}